name: Pylint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt install libhamlib-utils
        python -m pip install --upgrade pip
        python -m pip install pylint
    - name: Analyse with pylint
      run: |
        pylint --rcfile .pylintrc `ls *.py svarog_ctl/*.py|grep .py$|xargs`
