name: Pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      uses: actions/setup-python@v4
      with:
        python-version: |
          3.9
          3.10
          3.11
    - name: Install dependencies
      run: |
        sudo apt install libhamlib-utils
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    - name: Run unit tests with pytest
      run: |
        python -m pytest -s -v
