name: Pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt install libhamlib-utils
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    - name: Run unit tests with pytest
      run: |
        pytest -s -v
